spring:
  application:
    name: zuul

#配置zuul 的路由分发 /api/sso/** 都由sso 服务处理
#routes 配置多个。zuul 中 配置的路由 都会 经过 zuul 的过滤器
zuul:
  routes:
    api-sso:
      path: /api/sso/**
      serviceId: sso
  #忽略的 url，只要配置忽略，就会忽略哪怕 routes 中配置了
  ignored-patterns: /api/sso/**