#springCloud config 统一配置管理
spring:
  cloud:
    config:
      server:
        git:
        #存放配置文件的git 地址
          uri: https://github.com/yoxiyoxiiii/auth-config-repo
  application:
    name: config
#  rabbitmq:
#    host: lcoahost
#    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  health:
    rabbit:
      enabled: true
  info:
    git:
      enabled: true
  security:
    enabled: false

